/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package four_in_one_games;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class GameSelection extends javax.swing.JFrame {

    /**
     * Creates new form GameSelection
     */
    public GameSelection() {
        initComponents();
        String underline = "<html><u>EXIT</u></html>";
        exit.setText(underline);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        exit = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JTextField();
        title3 = new javax.swing.JTextField();
        title4 = new javax.swing.JTextField();
        title5 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setForeground(new java.awt.Color(0, 153, 255));
        exit.setText("EXIT");
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        title1.setFont(new java.awt.Font("OCR A Extended", 3, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 153, 255));
        title1.setText("WELCOME!!!");
        getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));

        title2.setEditable(false);
        title2.setBackground(new java.awt.Color(0, 0, 0));
        title2.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        title2.setForeground(new java.awt.Color(0, 153, 255));
        title2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        title2.setText("GUESSING NUMBER");
        title2.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 170, -1));

        title3.setEditable(false);
        title3.setBackground(new java.awt.Color(0, 0, 0));
        title3.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        title3.setForeground(new java.awt.Color(0, 153, 255));
        title3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        title3.setText("PUZZLE GAME");
        title3.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 240, 170, -1));

        title4.setEditable(false);
        title4.setBackground(new java.awt.Color(0, 0, 0));
        title4.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        title4.setForeground(new java.awt.Color(0, 153, 255));
        title4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        title4.setText("TIC TAC TOE");
        title4.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 440, 170, -1));

        title5.setEditable(false);
        title5.setBackground(new java.awt.Color(0, 0, 0));
        title5.setFont(new java.awt.Font("OCR A Extended", 3, 12)); // NOI18N
        title5.setForeground(new java.awt.Color(0, 153, 255));
        title5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        title5.setText("SNAKE GAME");
        title5.setBorder(javax.swing.BorderFactory.createBevelBorder(0, new java.awt.Color(204, 204, 204), new java.awt.Color(204, 204, 204)));
        getContentPane().add(title5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 170, -1));

        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 170, 170));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/four_in_one_games/Assets/shtxz.jpg"))); // NOI18N
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, 170));

        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 255), 1, true));
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 170, 170));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/four_in_one_games/Assets/guessnum.png"))); // NOI18N
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 170, 170));

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        this.dispose();
        PuzzleGame pg = new PuzzleGame();
        pg.setVisible(true);
        pg.setLocationRelativeTo(null);
        pg.pack();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        this.dispose();
        GuessingGame gg = new GuessingGame();
        gg.setVisible(true);
        gg.setLocationRelativeTo(null);
        gg.pack();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        this.dispose();
        TicTacToe ttt = new TicTacToe();
        ttt.setVisible(true);
        ttt.setLocationRelativeTo(null);
        ttt.pack();
    }//GEN-LAST:event_jLabel3MouseClicked
private JFrame frame;
    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        frame = new JFrame("EXIT!");
        if(JOptionPane.showConfirmDialog(frame,"Are You Sure You Want To Exit?","Game Selection",JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_exitMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
            this.dispose();  // Close the GameSelection window first
            Snake s = new Snake();
            s.setVisible(true);  // Make the Snake window visible
            s.setLocationRelativeTo(null);  // Center the window
    }//GEN-LAST:event_jLabel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameSelection().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField title2;
    private javax.swing.JTextField title3;
    private javax.swing.JTextField title4;
    private javax.swing.JTextField title5;
    // End of variables declaration//GEN-END:variables
}
