/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package four_in_one_games;

/**
 *
 * @author ACER
 */
import com.sun.glass.events.KeyEvent;
import java.util.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
public class GuessingGame extends javax.swing.JFrame {

    /**
     * Creates new form GuessingGame
     */
    public int value;
    private static int tries = 3;
    private JFrame frame;
    int i, num, guess, nearVal;
    Random rand;
    public GuessingGame() {
        initComponents();
        playagain.setVisible(false);
        yesBTN.setVisible(false);
        noBTN.setVisible(false);
    }
    
    public void shuffle(){
        rand = new Random();
        for(i = 1; i <= 100; i++){
            value = rand.nextInt(i);
            randomtxt.setText("" + value);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noBTN = new javax.swing.JButton();
        yesBTN = new javax.swing.JButton();
        hint = new javax.swing.JLabel();
        guesstxt = new javax.swing.JTextField();
        result = new javax.swing.JLabel();
        shuffleBTN = new javax.swing.JButton();
        playagain = new javax.swing.JLabel();
        warningStart = new javax.swing.JLabel();
        randomtxt = new javax.swing.JTextField();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        noBTN.setBackground(new java.awt.Color(255, 51, 51));
        noBTN.setFont(new java.awt.Font("Elephant", 0, 10)); // NOI18N
        noBTN.setForeground(new java.awt.Color(255, 255, 255));
        noBTN.setText("NO");
        noBTN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        noBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noBTNActionPerformed(evt);
            }
        });
        getContentPane().add(noBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 50, 20));

        yesBTN.setBackground(new java.awt.Color(51, 153, 255));
        yesBTN.setFont(new java.awt.Font("Elephant", 0, 10)); // NOI18N
        yesBTN.setForeground(new java.awt.Color(255, 255, 255));
        yesBTN.setText("YES");
        yesBTN.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(0, 0, 0))); // NOI18N
        yesBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesBTNActionPerformed(evt);
            }
        });
        getContentPane().add(yesBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 50, 20));

        hint.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        hint.setForeground(new java.awt.Color(255, 255, 255));
        hint.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(hint, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 560, 30));

        guesstxt.setBackground(new java.awt.Color(0, 0, 0));
        guesstxt.setFont(new java.awt.Font("Elephant", 0, 70)); // NOI18N
        guesstxt.setForeground(new java.awt.Color(255, 255, 255));
        guesstxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        guesstxt.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, null));
        guesstxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                guesstxtKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                guesstxtKeyTyped(evt);
            }
        });
        getContentPane().add(guesstxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 210, 90));

        result.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        result.setForeground(new java.awt.Color(0, 0, 0));
        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(result, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 560, 50));

        shuffleBTN.setBackground(new java.awt.Color(0, 0, 0));
        shuffleBTN.setFont(new java.awt.Font("Elephant", 1, 24)); // NOI18N
        shuffleBTN.setForeground(new java.awt.Color(255, 255, 255));
        shuffleBTN.setText("Shuffle");
        shuffleBTN.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        shuffleBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shuffleBTNActionPerformed(evt);
            }
        });
        getContentPane().add(shuffleBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 130, 40));

        playagain.setForeground(new java.awt.Color(255, 51, 255));
        playagain.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        playagain.setText("**do you want to play again?");
        getContentPane().add(playagain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 560, -1));

        warningStart.setForeground(new java.awt.Color(255, 0, 0));
        warningStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningStart.setText("**press shuffle or space to start the game.");
        getContentPane().add(warningStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 560, -1));

        randomtxt.setEditable(false);
        randomtxt.setText("randomtxt");
        randomtxt.setBorder(null);
        getContentPane().add(randomtxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, -1, -1));

        background.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\WRIST\\question.gif")); // NOI18N
        background.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 340));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void shuffleBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shuffleBTNActionPerformed
        shuffle();
        warningStart.setVisible(false);
    }//GEN-LAST:event_shuffleBTNActionPerformed

    private void guesstxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guesstxtKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            nearVal = value + rand.nextInt(10);
            num = Integer.parseInt(randomtxt.getText());
            guess = Integer.parseInt(guesstxt.getText());
            
            if(num < guess){
                result.setText("LOWER!");
                guesstxt.setText("");
                if (tries == 0){
                    hint.setText("HINT: the number is near: "+ nearVal);
                }
                tries--;
            }
            else if(num > guess){
                result  .setText("HIGHER!");
                guesstxt.setText("")       ;
                if (tries == 0){
                    hint.setText("HINT: The Number is near: "+ nearVal);
                }
                tries--;
            }
            else if(num == guess){
                result.setText("WELL DONE! THE ANSWER IS " + value + "!");
                
                hint    .setText("");
                guesstxt.setText("");
                
                warningStart.setVisible(false);
                playagain   .setVisible(true );
                yesBTN      .setVisible(true );
                noBTN       .setVisible(true );
                
                tries = 3;
            }
            else{
                JOptionPane.showMessageDialog(null, "INVALID INPUT!");
            }
        }
        else if(Character.isLetter(evt.getKeyChar())){
            JOptionPane.showMessageDialog(null,"NUMBER IS ONLY ALLOWED IN THIS GAME!","INVALID INPUT!",0);
        }
        if(evt.getKeyCode() == KeyEvent.VK_SPACE){
            shuffle();
            warningStart.setVisible(false);
        }
    }//GEN-LAST:event_guesstxtKeyPressed

    private void yesBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesBTNActionPerformed
        hint.setText("");
        result.setText("");
        playagain.setVisible(false);
        warningStart.setVisible(true);
        yesBTN.setVisible(false);
        noBTN.setVisible(false);
    }//GEN-LAST:event_yesBTNActionPerformed

    private void noBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noBTNActionPerformed
        JOptionPane.showMessageDialog(null, "Navigating to Game Selection!");
        playagain.setVisible(false);
        GameSelection gs = new GameSelection();
        gs.setVisible(true);
        dispose();
    }//GEN-LAST:event_noBTNActionPerformed

    private void guesstxtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_guesstxtKeyTyped
        if(!Character.isDigit(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_guesstxtKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuessingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuessingGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField guesstxt;
    private javax.swing.JLabel hint;
    private javax.swing.JButton noBTN;
    private javax.swing.JLabel playagain;
    private javax.swing.JTextField randomtxt;
    private javax.swing.JLabel result;
    private javax.swing.JButton shuffleBTN;
    private javax.swing.JLabel warningStart;
    private javax.swing.JButton yesBTN;
    // End of variables declaration//GEN-END:variables
}
