/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package four_in_one_games;

import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class PuzzleGame extends javax.swing.JFrame {
    private JLabel[][] board;

    /**
     * Creates new form PuzzleGame
     */
    public PuzzleGame() {
        initComponents();
        NumOfClickslbl.setVisible(false);
        ClicksNum.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Number = new javax.swing.JPanel();
        num1 = new javax.swing.JButton();
        num2 = new javax.swing.JButton();
        num3 = new javax.swing.JButton();
        num4 = new javax.swing.JButton();
        num5 = new javax.swing.JButton();
        num6 = new javax.swing.JButton();
        num7 = new javax.swing.JButton();
        num8 = new javax.swing.JButton();
        numspace = new javax.swing.JButton();
        NumOfClickslbl = new javax.swing.JLabel();
        ClicksNum = new javax.swing.JLabel();
        warningStart = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        ShuffleBtn = new javax.swing.JButton();
        ExitBtn = new javax.swing.JButton();
        SolutionBtn = new javax.swing.JButton();
        HomeBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Number.setBackground(new java.awt.Color(0, 153, 204));
        Number.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Number.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        num1.setBackground(new java.awt.Color(0, 204, 255));
        num1.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        num1.setForeground(new java.awt.Color(0, 102, 255));
        num1.setText("1");
        num1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num1ActionPerformed(evt);
            }
        });
        Number.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 110, 100));

        num2.setBackground(new java.awt.Color(0, 204, 255));
        num2.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        num2.setForeground(new java.awt.Color(0, 102, 255));
        num2.setText("2");
        num2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num2ActionPerformed(evt);
            }
        });
        Number.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, 110, 100));

        num3.setBackground(new java.awt.Color(0, 204, 255));
        num3.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        num3.setForeground(new java.awt.Color(0, 102, 255));
        num3.setText("3");
        num3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num3ActionPerformed(evt);
            }
        });
        Number.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 110, 100));

        num4.setBackground(new java.awt.Color(0, 204, 255));
        num4.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        num4.setForeground(new java.awt.Color(0, 102, 255));
        num4.setText("4");
        num4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num4ActionPerformed(evt);
            }
        });
        Number.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 100));

        num5.setBackground(new java.awt.Color(0, 204, 255));
        num5.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        num5.setForeground(new java.awt.Color(0, 102, 255));
        num5.setText("5");
        num5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num5ActionPerformed(evt);
            }
        });
        Number.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 110, 100));

        num6.setBackground(new java.awt.Color(0, 204, 255));
        num6.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        num6.setForeground(new java.awt.Color(0, 102, 255));
        num6.setText("6");
        num6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num6ActionPerformed(evt);
            }
        });
        Number.add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 110, 100));

        num7.setBackground(new java.awt.Color(0, 204, 255));
        num7.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        num7.setForeground(new java.awt.Color(0, 102, 255));
        num7.setText("7");
        num7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num7ActionPerformed(evt);
            }
        });
        Number.add(num7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 110, 100));

        num8.setBackground(new java.awt.Color(0, 204, 255));
        num8.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        num8.setForeground(new java.awt.Color(0, 102, 255));
        num8.setText("8");
        num8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        num8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                num8ActionPerformed(evt);
            }
        });
        Number.add(num8, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 110, 100));

        numspace.setBackground(new java.awt.Color(0, 204, 255));
        numspace.setFont(new java.awt.Font("Eras Bold ITC", 1, 48)); // NOI18N
        numspace.setForeground(new java.awt.Color(0, 102, 255));
        numspace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        numspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numspaceActionPerformed(evt);
            }
        });
        Number.add(numspace, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 110, 100));

        NumOfClickslbl.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        NumOfClickslbl.setForeground(new java.awt.Color(0, 204, 204));
        NumOfClickslbl.setText("Number of Clicks: ");
        Number.add(NumOfClickslbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, -1, 70));

        ClicksNum.setFont(new java.awt.Font("Dubai", 0, 24)); // NOI18N
        ClicksNum.setForeground(new java.awt.Color(0, 204, 204));
        ClicksNum.setText("0");
        Number.add(ClicksNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 330, -1, 70));

        warningStart.setForeground(new java.awt.Color(255, 51, 255));
        warningStart.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        warningStart.setText("**press shuffle to start the game.");
        Number.add(warningStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 330, 430, 70));

        getContentPane().add(Number, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 390, 390));

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ShuffleBtn.setBackground(new java.awt.Color(0, 153, 204));
        ShuffleBtn.setText("SHUFFLE");
        ShuffleBtn.setBorder(new javax.swing.border.SoftBevelBorder(0));
        ShuffleBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ShuffleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShuffleBtnActionPerformed(evt);
            }
        });

        ExitBtn.setBackground(new java.awt.Color(0, 153, 204));
        ExitBtn.setText("EXIT");
        ExitBtn.setBorder(new javax.swing.border.SoftBevelBorder(0));
        ExitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        SolutionBtn.setBackground(new java.awt.Color(0, 153, 204));
        SolutionBtn.setText("SOLUTION");
        SolutionBtn.setBorder(new javax.swing.border.SoftBevelBorder(0));
        SolutionBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SolutionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SolutionBtnActionPerformed(evt);
            }
        });

        HomeBtn.setBackground(new java.awt.Color(0, 153, 204));
        HomeBtn.setText("HOME");
        HomeBtn.setBorder(new javax.swing.border.SoftBevelBorder(0));
        HomeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        HomeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HomeBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ShuffleBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HomeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExitBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(SolutionBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ExitBtn, ShuffleBtn, SolutionBtn});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShuffleBtn)
                    .addComponent(SolutionBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(HomeBtn)
                    .addComponent(ExitBtn))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 390, 90));
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 540));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    int Counter;
    
    void EmptySpotChecker(JButton numspace, JButton num2)
    {
        
        String ShuffleNumber = num2.getText();
        
        if("".equals(ShuffleNumber))
        {
            num2.setText(numspace.getText());
            numspace.setText("");
        }   
    }
    
    public void Shuffle()
    {
        int[] bnum = new int[9];
        int i, j, rowchecker;
        Boolean flag = false;
        
        i = 1;
        
        do
        {
            Random rnd = new Random();
            rowchecker = rnd.nextInt((8) + 1);
            
            for(j = 1; j <= i; j++)
            {
                if(bnum[j] == rowchecker)
                {
                    flag = true;
                    break;
                }
            }
            
            if(flag == true)
            {
                flag = false;
            }
            else
            {
                bnum[i] = rowchecker;
                i++;
            }
        }
        while(i <= 8);
            num1.setText(Integer.toString(bnum[1]));
            num2.setText(Integer.toString(bnum[2]));
            num3.setText(Integer.toString(bnum[3]));
            num4.setText(Integer.toString(bnum[4]));
            num5.setText(Integer.toString(bnum[5]));
            num6.setText(Integer.toString(bnum[6]));
            num7.setText(Integer.toString(bnum[7]));
            num8.setText(Integer.toString(bnum[8]));
            numspace.setText("");
    }
    
    public void NumCheck()
    {
        String b1 = num1.getText();
        String b2 = num2.getText();
        String b3 = num3.getText();
        String b4 = num4.getText();
        String b5 = num5.getText();
        String b6 = num6.getText();
        String b7 = num7.getText();
        String b8 = num8.getText();
        
        if("1".equals(b1) && "2".equals(b2) && "3".equals(b3) && "4".equals(b4) && 
           "5".equals(b5) && "6".equals(b6) && "7".equals(b7) && "8".equals(b8))
        {
            JOptionPane.showMessageDialog(this, "You wn the game with the total number of \n" + Counter + " clicks!"
                    ,"Congratulations!",JOptionPane.INFORMATION_MESSAGE);
            if(JOptionPane.showConfirmDialog(this,"Do you want to play again?","Puzzle Game",JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_NO_OPTION){
                num1.setText("1");
                num2.setText("2");
                num3.setText("3");
                num4.setText("4");
                num5.setText("5");
                num6.setText("6");
                num7.setText("7");
                num8.setText("8");
                numspace.setText("");
                Counter = 0;
                ClicksNum.setText(Integer.toString(Counter));
                warningStart.setVisible(true);
                NumOfClickslbl.setVisible(false);
                ClicksNum.setVisible(false);    
            }
            else{
                if(JOptionPane.showConfirmDialog(this,"Do you want to exit this application?"
                        ,"Puzzle Game",JOptionPane.YES_NO_OPTION)
                == JOptionPane.YES_NO_OPTION){
                    JOptionPane.showMessageDialog(this,"Exiting Application!");
                    System.exit(0);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Navigating to the Game Selection!");
                    GameSelection gs = new GameSelection();
                    this.dispose();
                    gs.setVisible(true);
                    gs.setLocationRelativeTo(null);
                    gs.pack();
                }
            }
//            Shuffle();
            Counter = -1;
            ClicksNum.setText(Integer.toString(Counter));
        }
        Counter++;
        ClicksNum.setText(Integer.toString(Counter));
    }
    
    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void HomeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HomeBtnActionPerformed
        GameSelection gs = new GameSelection();
        this.dispose();
        gs.setVisible(true);
        gs.setLocationRelativeTo(null);
        gs.pack();
    }//GEN-LAST:event_HomeBtnActionPerformed

    private void num1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num1ActionPerformed
        EmptySpotChecker(num1,num2);
        EmptySpotChecker(num1,num4);
        NumCheck();
    }//GEN-LAST:event_num1ActionPerformed

    private void num2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num2ActionPerformed
        EmptySpotChecker(num2,num1);
        EmptySpotChecker(num2,num3);
        EmptySpotChecker(num2,num5);
        NumCheck();
    }//GEN-LAST:event_num2ActionPerformed

    private void num3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num3ActionPerformed
        EmptySpotChecker(num3,num2);
        EmptySpotChecker(num3,num6);
        NumCheck();
    }//GEN-LAST:event_num3ActionPerformed

    private void num4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num4ActionPerformed
        EmptySpotChecker(num4,num1);
        EmptySpotChecker(num4,num5);
        EmptySpotChecker(num4,num7);
        NumCheck();
    }//GEN-LAST:event_num4ActionPerformed

    private void num5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num5ActionPerformed
        EmptySpotChecker(num5,num2);
        EmptySpotChecker(num5,num4);
        EmptySpotChecker(num5,num6);
        EmptySpotChecker(num5,num8);
        NumCheck();
    }//GEN-LAST:event_num5ActionPerformed

    private void num6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num6ActionPerformed
        EmptySpotChecker(num6,num3);
        EmptySpotChecker(num6,num5);
        EmptySpotChecker(num6,numspace);
        NumCheck();
    }//GEN-LAST:event_num6ActionPerformed

    private void num7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num7ActionPerformed
        EmptySpotChecker(num7,num4);
        EmptySpotChecker(num7,num8);
        NumCheck();
    }//GEN-LAST:event_num7ActionPerformed

    private void num8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_num8ActionPerformed
        EmptySpotChecker(num8,num5);
        EmptySpotChecker(num8,num7);
        EmptySpotChecker(num8,numspace);
        NumCheck();
    }//GEN-LAST:event_num8ActionPerformed

    private void numspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numspaceActionPerformed
        EmptySpotChecker(numspace,num6);
        EmptySpotChecker(numspace,num8);
        NumCheck();
    }//GEN-LAST:event_numspaceActionPerformed

    private void ShuffleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShuffleBtnActionPerformed
        Shuffle();
        NumOfClickslbl.setVisible(true);
        ClicksNum.setVisible(true);
        warningStart.setVisible(false);
        Counter = 0;
        ClicksNum.setText(Integer.toString(Counter));
    }//GEN-LAST:event_ShuffleBtnActionPerformed

    private void SolutionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SolutionBtnActionPerformed
        num1.setText("1");
        num2.setText("2");
        num3.setText("3");
        num4.setText("4");
        num5.setText("5");
        num6.setText("6");
        num7.setText("7");
        num8.setText("8");
        numspace.setText("");
        Counter = 0;
        ClicksNum.setText(Integer.toString(Counter));
        warningStart.setVisible(true);
        NumOfClickslbl.setVisible(false);
        ClicksNum.setVisible(false);
    }//GEN-LAST:event_SolutionBtnActionPerformed
        
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PuzzleGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PuzzleGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ClicksNum;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton HomeBtn;
    private javax.swing.JLabel NumOfClickslbl;
    private javax.swing.JPanel Number;
    private javax.swing.JButton ShuffleBtn;
    private javax.swing.JButton SolutionBtn;
    private javax.swing.JLabel background;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton num1;
    private javax.swing.JButton num2;
    private javax.swing.JButton num3;
    private javax.swing.JButton num4;
    private javax.swing.JButton num5;
    private javax.swing.JButton num6;
    private javax.swing.JButton num7;
    private javax.swing.JButton num8;
    private javax.swing.JButton numspace;
    private javax.swing.JLabel warningStart;
    // End of variables declaration//GEN-END:variables
}
