/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package four_in_one_games;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicProgressBarUI;

/**
 *
 * @author Daxxtropezz
 */
public class SplashScreen extends javax.swing.JFrame {

    /**
     * Creates new form SplashScreen
     */

    public SplashScreen() {
        initComponents();
        loadingBar.setUI(new BasicProgressBarUI(){});
        startBTN.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBG = new javax.swing.JPanel();
        title1 = new javax.swing.JLabel();
        title2 = new javax.swing.JLabel();
        title3 = new javax.swing.JLabel();
        title4 = new javax.swing.JLabel();
        loadingValue = new javax.swing.JLabel();
        loadingText = new javax.swing.JLabel();
        startBTN = new javax.swing.JLabel();
        loadingBar = new javax.swing.JProgressBar();
        GIFbg = new javax.swing.JLabel();
        bgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanelBG.setBackground(new java.awt.Color(0, 204, 255));
        jPanelBG.setPreferredSize(new java.awt.Dimension(926, 546));
        jPanelBG.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title1.setFont(new java.awt.Font("OCR A Extended", 3, 48)); // NOI18N
        title1.setForeground(new java.awt.Color(0, 153, 255));
        title1.setText("ZONE");
        jPanelBG.add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, -1, -1));

        title2.setFont(new java.awt.Font("OCR A Extended", 3, 48)); // NOI18N
        title2.setForeground(new java.awt.Color(0, 102, 204));
        title2.setText("GAME");
        jPanelBG.add(title2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        title3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/four_in_one_games/Assets/9's.gif"))); // NOI18N
        jPanelBG.add(title3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, -1, 110));

        title4.setFont(new java.awt.Font("OCR A Extended", 3, 48)); // NOI18N
        title4.setForeground(new java.awt.Color(0, 102, 204));
        title4.setText("'S ");
        jPanelBG.add(title4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, -1, -1));

        loadingValue.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingValue.setForeground(new java.awt.Color(0, 255, 255));
        loadingValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadingValue.setText("100 %");
        jPanelBG.add(loadingValue, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 80, -1));

        loadingText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        loadingText.setForeground(new java.awt.Color(51, 255, 255));
        loadingText.setText("Loading...");
        jPanelBG.add(loadingText, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 490, -1));

        startBTN.setFont(new java.awt.Font("OCR A Extended", 3, 24)); // NOI18N
        startBTN.setForeground(new java.awt.Color(0, 153, 255));
        startBTN.setText("START");
        startBTN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startBTNMouseClicked(evt);
            }
        });
        jPanelBG.add(startBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, 90, -1));

        loadingBar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 204, 255)));
        jPanelBG.add(loadingBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 490, 20));

        GIFbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/four_in_one_games/Assets/shha.gif"))); // NOI18N
        GIFbg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 204, 204)));
        GIFbg.setMaximumSize(new java.awt.Dimension(926, 546));
        GIFbg.setPreferredSize(new java.awt.Dimension(926, 546));
        jPanelBG.add(GIFbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 490, 250));

        bgImage.setIcon(new javax.swing.ImageIcon("C:\\Users\\ACER\\Downloads\\CIRC.gif")); // NOI18N
        jPanelBG.add(bgImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 770, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBG, javax.swing.GroupLayout.DEFAULT_SIZE, 540, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void startBTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startBTNMouseClicked
        dispose();
        GameSelection gs = new GameSelection();
        gs.setVisible(true);
    }//GEN-LAST:event_startBTNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SplashScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

       SplashScreen load = new SplashScreen();
       load.setVisible(true);

       try{
           for(int loading = 0;loading <= 100; loading++){
               //Thread.sleep(100);
               load.loadingValue.setText(loading + "%");
               
               if(loading <= 10){
                   Thread.sleep((long)(Math.random()*150));
                   load.loadingText.setText(" Loading panels...");
               }else if(loading <= 20){
                   Thread.sleep((long)(Math.random()*200));
                   load.loadingText.setText(" Preparing screens...");
               }else if(loading <= 50){
                   Thread.sleep((long)(Math.random()*300));
                   load.loadingText.setText(" Loading games...");
               }else if(loading <= 75){
                   Thread.sleep((long)(Math.random()*500));
                   load.loadingText.setText(" Games loaded successfully...");
               }else if(loading <= 80){
                   Thread.sleep((long)(Math.random()*1000));
                   loading = loading + 2;
                   load.loadingText.setText(" Launching application...");
               }else if(loading <= 90){
                   Thread.sleep((long)(Math.random()*1000));
                   load.loadingText.setText(" Launching application... Please wait.");
               }else if(loading == 100){
                   load.loadingText.setText(" Loading completed...");
                   load.startBTN.setVisible(true);
                   for(int startLoad = 0; startLoad<100;startLoad++){
                       if(startLoad <= 1){
                           load.startBTN.setText("START");
                       }else if(startLoad <= 5){
                           load.startBTN.setText("");
                       }
                       startLoad = 0;
                   }
               }
               load.loadingBar.setValue(loading);
           }
       }catch (Exception e){
           JOptionPane.showMessageDialog(null, e);           
       }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GIFbg;
    private javax.swing.JLabel bgImage;
    private javax.swing.JPanel jPanelBG;
    private javax.swing.JProgressBar loadingBar;
    private javax.swing.JLabel loadingText;
    private javax.swing.JLabel loadingValue;
    private javax.swing.JLabel startBTN;
    private javax.swing.JLabel title1;
    private javax.swing.JLabel title2;
    private javax.swing.JLabel title3;
    private javax.swing.JLabel title4;
    // End of variables declaration//GEN-END:variables
}
